const RESPONSE_SCALE = [
  { value: 1, label: "Completamente en desacuerdo", shortLabel: "Muy en desacuerdo" },
  { value: 2, label: "En desacuerdo", shortLabel: "En desacuerdo" },
  { value: 3, label: "Ni de acuerdo ni en desacuerdo", shortLabel: "Neutral" },
  { value: 4, label: "De acuerdo", shortLabel: "De acuerdo" },
  { value: 5, label: "Completamente de acuerdo", shortLabel: "Muy de acuerdo" },
];

const DIMENSIONS = {
  asertividad_directa: {
    key: "asertividad_directa",
    label: "Asertividad directa",
    type: "resource",
    // Reactivos de expresión abierta, defensa de derechos y petición directa en interacción presencial.
    rationale:
      "Agrupa conductas de expresión abierta de opiniones, necesidades, afecto, peticiones y manejo directo de la crítica.",
  },
  no_asertividad: {
    key: "no_asertividad",
    label: "No asertividad",
    type: "risk",
    // Reactivos que expresan inhibición, evitación, temor a la crítica o dificultad para expresar deseos y desacuerdos.
    rationale:
      "Agrupa indicadores de inhibición interpersonal, evitación, temor a la crítica y dificultad para expresar necesidades o desacuerdos.",
  },
  asertividad_indirecta: {
    key: "asertividad_indirecta",
    label: "Asertividad indirecta",
    type: "risk",
    // Reactivos donde la persona expresa que le resulta más fácil comunicarse de manera mediada (teléfono, carta, escrito) que cara a cara.
    rationale:
      "Agrupa patrones de expresión por vías indirectas como teléfono, cartas o medios escritos en lugar de la interacción personal directa.",
  },
};

const QUESTIONS = [
  {
    id: 1,
    text: "Puedo reconocer públicamente que cometí un error.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Admitir errores en público implica autoafirmación y manejo abierto de la propia conducta.",
  },
  {
    id: 2,
    text: "No soy capaz de expresar abiertamente lo que realmente pienso.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa inhibición para comunicar opiniones propias.",
  },
  {
    id: 3,
    text: "Me cuesta trabajo expresar lo que pienso en presencia de otros.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Indica dificultad para autoexpresión frente a otras personas.",
  },
  {
    id: 4,
    text: "Me es más fácil decirle a alguien que acepto su crítica hacia mi persona por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Ubica una preferencia por canal indirecto frente a la interacción personal.",
  },
  {
    id: 5,
    text: "Me es difícil expresar mis deseos.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja un obstáculo para formular deseos propios.",
  },
  {
    id: 6,
    text: "Me es difícil expresar abiertamente mis sentimientos.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa dificultad para mostrar afectos y estados personales.",
  },
  {
    id: 7,
    text: "Puedo decirle a alguien directamente que actuó de manera injusta.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Implica señalar un trato injusto de forma clara y directa.",
  },
  {
    id: 8,
    text: "Cuando discuto con una persona acerca del lugar donde vamos a comer, yo expreso mi preferencia.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Refleja expresión directa de preferencias cotidianas.",
  },
  {
    id: 9,
    text: "Me cuesta trabajo hacer nuevos(as) amigos(as).",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Sugiere dificultad de aproximación interpersonal y apertura social.",
  },
  {
    id: 10,
    text: "No soy capaz de expresar abiertamente lo que deseo.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa limitación para comunicar deseos en forma abierta.",
  },
  {
    id: 11,
    text: "Puedo agradecer un halago acerca de mi apariencia personal.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Aceptar reconocimiento interpersonal sin evitación es una conducta asertiva.",
  },
  {
    id: 12,
    text: "Si tengo alguna duda, pido que se me aclare.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Pedir aclaraciones es una conducta de autoafirmación y búsqueda activa de información.",
  },
  {
    id: 13,
    text: "Cuando conozco a una persona, usualmente tengo poco que decirle.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja inhibición al iniciar contacto interpersonal.",
  },
  {
    id: 14,
    text: "Solicito ayuda cuando la necesito.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Pedir ayuda de forma explícita es una conducta asertiva funcional.",
  },
  {
    id: 15,
    text: "Cuando me doy cuenta de que me están cobrando de más, no digo nada.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa dificultad para defender derechos o corregir situaciones injustas.",
  },
  {
    id: 16,
    text: "Me es más fácil pedir que me devuelvan las cosas que he prestado por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Se refiere a la recuperación de pertenencias por un medio indirecto.",
  },
  {
    id: 17,
    text: "Me es fácil aceptar una crítica.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Aceptar críticas sin evitación o defensividad se relaciona con la asertividad.",
  },
  {
    id: 18,
    text: "Me es más fácil pedir prestado algo por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Describe preferencia por solicitar recursos por vía indirecta.",
  },
  {
    id: 19,
    text: "Puedo pedir favores.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Pedir favores se relaciona con la expresión directa de necesidades.",
  },
  {
    id: 20,
    text: "Expreso con mayor facilidad mi desagrado por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Se ubica en la expresión de desagrado por vía mediada.",
  },
  {
    id: 21,
    text: "Expreso amor y afecto a la gente que quiero.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Mide la expresión directa de afecto en el vínculo cercano.",
  },
  {
    id: 22,
    text: "Me molesta que me digan los errores que he cometido.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja reactividad ante la crítica y menor apertura interpersonal.",
  },
  {
    id: 23,
    text: "Puedo expresar mi amor más fácilmente por medio de una carta que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Ubica la expresión afectiva preferentemente en un medio indirecto.",
  },
  {
    id: 24,
    text: "Puedo decirles a las personas que actuaron injustamente, más fácilmente por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Traslada el desacuerdo a un canal menos directo que la interacción cara a cara.",
  },
  {
    id: 25,
    text: "Prefiero decirle a alguien que deseo estar solo(a) por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Describe la expresión indirecta de límites personales.",
  },
  {
    id: 26,
    text: "Platico abiertamente con una persona sobre las críticas hechas a mi conducta.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Mide apertura para conversar de forma directa sobre observaciones hacia la propia conducta.",
  },
  {
    id: 27,
    text: "Puedo pedir que me enseñen cómo hacer algo que no sé cómo realizar.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Refleja la capacidad de pedir orientación y aprendizaje sin inhibición.",
  },
  {
    id: 28,
    text: "Puedo expresar mi cariño con mayor facilidad por medio de tarjetas o cartas que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa afecto por medios escritos más que presenciales.",
  },
  {
    id: 29,
    text: "Me es más fácil hacer un cumplido por medio de una tarjeta o carta que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Los elogios se formulan con mayor facilidad en medios indirectos.",
  },
  {
    id: 30,
    text: "Es difícil para mí alabar a otros.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Mide dificultad para expresar reconocimiento interpersonal.",
  },
  {
    id: 31,
    text: "Me es difícil iniciar una conversación.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa inhibición al iniciar un intercambio social.",
  },
  {
    id: 32,
    text: "Es más fácil rehusarme a ir a un lugar al que no deseo ir por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "La negativa se expresa con más facilidad por vía indirecta.",
  },
  {
    id: 33,
    text: "Encuentro difícil admitir que estoy equivocado(a).",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Indica resistencia para reconocer errores frente a otros.",
  },
  {
    id: 34,
    text: "Me da pena participar en las pláticas por temor a la opinión de los demás.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Mide temor evaluativo e inhibición en conversaciones grupales.",
  },
  {
    id: 35,
    text: "Me es más fácil decir que no deseo ir a una fiesta por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja preferencia por rehusar invitaciones por vía indirecta.",
  },
  {
    id: 36,
    text: "Puedo expresar mis sentimientos más fácilmente por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Ubica la expresión emocional en un medio menos directo que el cara a cara.",
  },
  {
    id: 37,
    text: "Puedo admitir que cometí un error con mayor facilidad por teléfono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Describe el reconocimiento de errores por vía indirecta.",
  },
  {
    id: 38,
    text: "Acepto sin temor una crítica.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Supone tolerancia a la retroalimentación y expresión abierta ante ella.",
  },
  {
    id: 39,
    text: "Me da pena hablar frente a un grupo por temor a la crítica.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Indica inhibición social por miedo a la evaluación del grupo.",
  },
  {
    id: 40,
    text: "Prefiero decirle a alguien lo que deseo en la vida por escrito que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa proyectos o deseos vitales por escrito antes que en persona.",
  },
  {
    id: 41,
    text: "Me es difícil disculparme cuando tengo la culpa.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja dificultad para reparar interpersonalmente mediante disculpa.",
  },
  {
    id: 42,
    text: "Me cuesta trabajo decirle a otros lo que me molesta.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Mide dificultad para expresar molestia o desacuerdo directo.",
  },
  {
    id: 43,
    text: "Me da pena preguntar cuando tengo dudas.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Indica inhibición para pedir información o aclaraciones.",
  },
  {
    id: 44,
    text: "Me es más fácil expresar mi opinión por medio de una carta que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Ubica la opinión personal en un canal escrito en lugar de uno presencial.",
  },
  {
    id: 45,
    text: "Me es difícil empezar una relación con personas que acabo de conocer.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja dificultad para establecer vínculos con personas nuevas.",
  },
];

function getInstrumentDefinition() {
  return {
    title: "Escala Multidimensional de Asertividad (aplicación orientativa)",
    description:
      "Instrumento autoaplicado de 45 afirmaciones para explorar patrones de asertividad en estudiantes. Su uso en esta app es orientativo y académico.",
    responseScale: RESPONSE_SCALE,
    dimensions: Object.values(DIMENSIONS),
    questions: QUESTIONS,
  };
}

module.exports = {
  RESPONSE_SCALE,
  DIMENSIONS,
  QUESTIONS,
  getInstrumentDefinition,
};
