const RESPONSE_SCALE = [
  { value: 1, label: "Completamente en desacuerdo", shortLabel: "Muy en desacuerdo" },
  { value: 2, label: "En desacuerdo", shortLabel: "En desacuerdo" },
  { value: 3, label: "Ni de acuerdo ni en desacuerdo", shortLabel: "Neutral" },
  { value: 4, label: "De acuerdo", shortLabel: "De acuerdo" },
  { value: 5, label: "Completamente de acuerdo", shortLabel: "Muy de acuerdo" },
];

const DIMENSIONS = {
  asertividad_directa: {
    key: "asertividad_directa",
    label: "Asertividad directa",
    type: "resource",
    // Reactivos de expresion abierta, defensa de derechos y peticion directa en interaccion presencial.
    rationale:
      "Agrupa conductas de expresion abierta de opiniones, necesidades, afecto, peticiones y manejo directo de la critica.",
  },
  no_asertividad: {
    key: "no_asertividad",
    label: "No asertividad",
    type: "risk",
    // Reactivos que expresan inhibicion, evitacion, temor a la critica o dificultad para expresar deseos y desacuerdos.
    rationale:
      "Agrupa indicadores de inhibicion interpersonal, evitacion, temor a la critica y dificultad para expresar necesidades o desacuerdos.",
  },
  asertividad_indirecta: {
    key: "asertividad_indirecta",
    label: "Asertividad indirecta",
    type: "risk",
    // Reactivos donde la persona expresa que le resulta mas facil comunicarse de manera mediada (telefono, carta, escrito) que cara a cara.
    rationale:
      "Agrupa patrones de expresion por vias indirectas como telefono, cartas o medios escritos en lugar de la interaccion personal directa.",
  },
};

const QUESTIONS = [
  {
    id: 1,
    text: "Puedo reconocer publicamente que cometi un error.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Admitir errores en publico implica autoafirmacion y manejo abierto de la propia conducta.",
  },
  {
    id: 2,
    text: "No soy capaz de expresar abiertamente lo que realmente pienso.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa inhibicion para comunicar opiniones propias.",
  },
  {
    id: 3,
    text: "Me cuesta trabajo expresar lo que pienso en presencia de otros.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Indica dificultad para autoexpresion frente a otras personas.",
  },
  {
    id: 4,
    text: "Me es mas facil decirle a alguien que acepto su critica a mi persona, por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Ubica una preferencia por canal indirecto frente a la interaccion personal.",
  },
  {
    id: 5,
    text: "Me es dificil expresar mis deseos.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja obstaculo para formular deseos propios.",
  },
  {
    id: 6,
    text: "Me es dificil expresar abiertamente mis sentimientos.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa dificultad para mostrar afectos y estados personales.",
  },
  {
    id: 7,
    text: "Puedo decirle a alguien directamente que actuo de manera injusta.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Implica senalar un trato injusto de forma clara y directa.",
  },
  {
    id: 8,
    text: "Cuando discuto con una persona acerca del lugar donde vamos a comer, yo expreso mi preferencia.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Refleja expresion directa de preferencias cotidianas.",
  },
  {
    id: 9,
    text: "Me cuesta trabajo hacer nuevos(as) amigos(as).",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Sugiere dificultad de aproximacion interpersonal y apertura social.",
  },
  {
    id: 10,
    text: "No soy capaz de expresar abiertamente lo que deseo.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa limitacion para comunicar deseos en forma abierta.",
  },
  {
    id: 11,
    text: "Puedo agradecer un halago hecho acerca de mi apariencia personal.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Aceptar reconocimiento interpersonal sin evitacion es una conducta asertiva.",
  },
  {
    id: 12,
    text: "Si tengo alguna duda, pido que se me aclare.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Pedir aclaraciones es una conducta de autoafirmacion y busqueda activa de informacion.",
  },
  {
    id: 13,
    text: "Cuando conozco a una persona, usualmente tengo poco que decirle.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja inhibicion al iniciar contacto interpersonal.",
  },
  {
    id: 14,
    text: "Solicito ayuda cuando la necesito.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Pedir ayuda de forma explicita es una conducta asertiva funcional.",
  },
  {
    id: 15,
    text: "Cuando me doy cuenta de que me estan cobrando de mas, no digo nada.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa dificultad para defender derechos o corregir situaciones injustas.",
  },
  {
    id: 16,
    text: "Me es mas facil pedir que me devuelvan las cosas que he prestado, por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Se refiere a recuperacion de pertenencias por un medio indirecto.",
  },
  {
    id: 17,
    text: "Me es facil aceptar una critica.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Aceptar critica sin evitacion o defensividad se relaciona con asertividad.",
  },
  {
    id: 18,
    text: "Me es mas facil pedir prestado algo, por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Describe preferencia por solicitar recursos via indirecta.",
  },
  {
    id: 19,
    text: "Puedo pedir favores.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Pedir favores se relaciona con expresion directa de necesidades.",
  },
  {
    id: 20,
    text: "Expreso con mayor facilidad mi desagrado por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Se ubica en expresion de desagrado por via mediada.",
  },
  {
    id: 21,
    text: "Expreso amor y afecto a la gente que quiero.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Mide expresion directa de afecto en el vinculo cercano.",
  },
  {
    id: 22,
    text: "Me molesta que me digan los errores que he cometido.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja reactividad ante la critica y menor apertura interpersonal.",
  },
  {
    id: 23,
    text: "Puedo expresar mi amor mas facilmente por medio de una carta que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Ubica la expresion afectiva preferentemente en un medio indirecto.",
  },
  {
    id: 24,
    text: "Puedo decirle a las personas que actuaron injustamente, mas facilmente por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Traslada el desacuerdo a un canal menos directo que la interaccion cara a cara.",
  },
  {
    id: 25,
    text: "Prefiero decirle a alguien que deseo estar solo(a), por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Describe expresion indirecta de limites personales.",
  },
  {
    id: 26,
    text: "Platico abiertamente con una persona las criticas hechas a mi conducta.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Mide apertura para conversar de forma directa sobre observaciones hacia la propia conducta.",
  },
  {
    id: 27,
    text: "Puedo pedir que me ensenen como hacer algo que no se como realizar.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Refleja capacidad de pedir orientacion y aprendizaje sin inhibicion.",
  },
  {
    id: 28,
    text: "Puedo expresar mi carino con mayor facilidad por medio de tarjetas o cartas que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa afecto por medios escritos mas que presenciales.",
  },
  {
    id: 29,
    text: "Me es mas facil hacer un cumplido, por medio de una tarjeta o carta que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Los elogios se formulan con mayor facilidad en medios indirectos.",
  },
  {
    id: 30,
    text: "Es dificil para mi alabar a otros.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Mide dificultad para expresar reconocimiento interpersonal.",
  },
  {
    id: 31,
    text: "Me es dificil iniciar una conversacion.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa inhibicion al iniciar intercambio social.",
  },
  {
    id: 32,
    text: "Es mas facil rehusarme ir a un lugar al que no deseo ir, por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "La negativa se expresa con mas facilidad por via indirecta.",
  },
  {
    id: 33,
    text: "Encuentro dificil admitir que estoy equivocado(a).",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Indica resistencia para reconocer errores frente a otros.",
  },
  {
    id: 34,
    text: "Me da pena participar en las platicas por temor a la opinion de los demas.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Mide temor evaluativo e inhibicion en conversaciones grupales.",
  },
  {
    id: 35,
    text: "Me es mas facil decir que no deseo ir a una fiesta, por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja preferencia por rehusar invitaciones por via indirecta.",
  },
  {
    id: 36,
    text: "Puedo expresar mis sentimientos mas facilmente por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Ubica expresion emocional en un medio menos directo que el cara a cara.",
  },
  {
    id: 37,
    text: "Puedo admitir que cometi un error, con mayor facilidad por telefono que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Describe reconocimiento de errores por via indirecta.",
  },
  {
    id: 38,
    text: "Acepto sin temor una critica.",
    dimension: "asertividad_directa",
    reverseForGlobal: false,
    scoringDirection: "directa",
    rationale: "Supone tolerancia a la retroalimentacion y expresion abierta ante ella.",
  },
  {
    id: 39,
    text: "Me da pena hablar frente a un grupo por temor a la critica.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Indica inhibicion social por miedo a la evaluacion del grupo.",
  },
  {
    id: 40,
    text: "Prefiero decirle a alguien sobre lo que deseo en la vida, por escrito que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Expresa proyectos o deseos vitales por escrito antes que en persona.",
  },
  {
    id: 41,
    text: "Me es dificil disculparme cuando tengo la culpa.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja dificultad para reparar interpersonalmente mediante disculpa.",
  },
  {
    id: 42,
    text: "Me cuesta trabajo decirle a otros lo que me molesta.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Mide dificultad para expresar molestia o desacuerdo directo.",
  },
  {
    id: 43,
    text: "Me da pena preguntar cuando tengo dudas.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Indica inhibicion para pedir informacion o aclaraciones.",
  },
  {
    id: 44,
    text: "Me es mas facil expresar mi opinion por medio de una carta que personalmente.",
    dimension: "asertividad_indirecta",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Ubica opinion personal en un canal escrito en lugar de uno presencial.",
  },
  {
    id: 45,
    text: "Me es dificil empezar una relacion con personas que acabo de conocer.",
    dimension: "no_asertividad",
    reverseForGlobal: true,
    scoringDirection: "inversa",
    rationale: "Refleja dificultad para establecer vinculos con personas nuevas.",
  },
];

function getInstrumentDefinition() {
  return {
    title: "Escala Multidimensional de Asertividad (aplicacion orientativa)",
    description:
      "Instrumento autoaplicado de 45 afirmaciones para explorar patrones de asertividad en estudiantes. Su uso en esta app es orientativo y academico.",
    responseScale: RESPONSE_SCALE,
    dimensions: Object.values(DIMENSIONS),
    questions: QUESTIONS,
  };
}

module.exports = {
  RESPONSE_SCALE,
  DIMENSIONS,
  QUESTIONS,
  getInstrumentDefinition,
};
